### ISSUE TITLE
Placing block shows up on other side of parcel

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#28]
Place block on one side of the parcel and it shows on the other

Reproduced
https://cdn.discordapp.com/attachments/469095615654002688/587894674291949590/bug.mov

See: https://www.cryptovoxels.com/play?coords=E@199E,3U,157N

**Comment by bnolan** [comment]
Looking into this now...

**Comment by bnolan** [comment]
Ok, I just tested on these two parcels `719` and `786` - where you linked to - and I can't replicate the bug - I think it was fixed in my fix for the off by one error. Re-open this issue if it's still happening, with a link to the parcel where t's happening (in case I got the wrong one). What browser too? :)
